# Import FastAPI's testing client
from fastapi.testclient import TestClient

# Import our FastAPI application
from main import app

# SQLAlchemy tools for creating our TEST database
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# pytest gives us fixtures
import pytest

# Import our Author model because a Book needs an author_id
from model import Author

# Import the common SQLAlchemy Base and FastAPI's real database dependency
from database import Base, get_db


# ============================================================
# 1. CREATE TEST DATABASE
# ============================================================

# This is a SEPARATE database from your real books.db
TEST_DATABASE_URL = "sqlite:///test_book.db"


# Create an engine connected to the test database
test_engine = create_engine(
    TEST_DATABASE_URL,

    # Required for SQLite when used with FastAPI/TestClient
    connect_args={"check_same_thread": False}
)


# Create database sessions that use test_book.db
TestingSessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=test_engine
)


# Create all SQLAlchemy tables inside test_book.db
#
# Your Base knows about:
#   Author
#   Book
#   User
#
# So these tables will be created in the test database.
Base.metadata.create_all(bind=test_engine)


# ============================================================
# 2. DATABASE FIXTURE
# ============================================================

@pytest.fixture
def db():
    # Start with a clean database
    Base.metadata.drop_all(bind=test_engine)

    # Create fresh tables
    Base.metadata.create_all(bind=test_engine)

    # Create a database session
    db = TestingSessionLocal()

    try:
        # Give the test the fresh database
        yield db

    finally:
        # Close the session
        db.close()

        # Remove all test tables after the test
        Base.metadata.drop_all(bind=test_engine)


# ============================================================
# 3. OVERRIDE FASTAPI'S DATABASE DEPENDENCY
# ============================================================

def override_get_db():
    # Instead of using your normal sessionLocal,
    # create a session connected to test_book.db
    db = TestingSessionLocal()

    try:
        # Give FastAPI the TEST database session
        yield db

    finally:
        # Close it after the request finishes
        db.close()


# Tell FastAPI:
#
# Whenever the application asks for:
#     Depends(get_db)
#
# use:
#     override_get_db()
#
# instead.
app.dependency_overrides[get_db] = override_get_db


# ============================================================
# 4. CREATE TEST CLIENT
# ============================================================

# TestClient allows us to send requests to FastAPI
# without opening Swagger or running Uvicorn.
client = TestClient(app)


# ============================================================
# 5. TEST GET /books
# ============================================================

def test_get_book():

    # Send GET request to our API
    response = client.get("/books")

    # Make sure API responded successfully
    assert response.status_code == 200


# ============================================================
# 6. TEST POST /books
# ============================================================

def test_create_book(db):

    # --------------------------------------------------------
    # Create an Author first
    # --------------------------------------------------------
    #
    # Book requires:
    #
    #     author_id = ForeignKey("author.id")
    #
    # So we need an author before creating a book.

    test_author = Author(name="Test Author")

    # Add author to TEST database
    db.add(test_author)

    # Save author
    db.commit()

    # Get the ID generated by the database
    db.refresh(test_author)


    # --------------------------------------------------------
    # Create Book request data
    # --------------------------------------------------------

    book = {
        "title": "Test Book",

        # Don't assume author_id = 1.
        # Use the ID that the test database actually generated.
        "author_id": test_author.id,

        "pages": 300,
        "price": 500
    }


    # Send POST request to FastAPI
    response = client.post(
        "/books/",
        json=book
    )


    # API should successfully create the book
    assert response.status_code == 200

def test_get_book_by_id(db):

    # Create an author
    author = Author(name="Test Author")

    db.add(author)
    db.commit()
    db.refresh(author)

    # Create a book through the API
    book = {
        "title": "Test Book",
        "author_id": author.id,
        "pages": 300,
        "price": 500
    }

    create_response = client.post("/books/", json=book)

    assert create_response.status_code == 200

    # Get the ID assigned to the new book
    book_id = create_response.json()["id"]

    # Now request that specific book
    response = client.get(f"/books/{book_id}")

    # It should exist
    assert response.status_code == 200

    # Check that we got the correct book
    assert response.json()["title"] == "Test Book"

def test_get_book_not_found(db):

    # Request an ID that should not exist
    response = client.get("/books/99999")

    # API should return "Not Found"
    assert response.status_code == 404

def test_create_book_invalid_data(db):

    book = {
        "title": "Bad Book",
        "author_id": "abc",
        "pages": 300,
        "price": 500
    }

    response = client.post("/books/", json=book)

    assert response.status_code == 422

def test_update_book(db):

    # Create an author first
    author = Author(name="Test Author")

    db.add(author)
    db.commit()
    db.refresh(author)

    # Create the original book
    book = {
        "title": "Original Book",
        "author_id": author.id,
        "pages": 200,
        "price": 300
    }

    create_response = client.post(
        "/books/",
        json=book
    )

    assert create_response.status_code == 200

    # Get the ID of the created book
    book_id = create_response.json()["id"]

    # Data we want to update
    updated_book = {
        "title": "Updated Book",
        "author_id": author.id,
        "pages": 500,
        "price": 750
    }

    # Send PUT request
    response = client.put(
        f"/books/{book_id}",
        json=updated_book
    )

    # Update should succeed
    assert response.status_code == 200

    # Verify the returned data
    data = response.json()

    assert data["title"] == "Updated Book"
    assert data["pages"] == 500
    assert data["price"] == 750

def test_update_book_not_found(db):

    updated_book = {
        "title": "Updated Book",
        "author_id": 1,
        "pages": 500,
        "price": 750
    }

    response = client.put(
        "/books/99999",
        json=updated_book
    )

    assert response.status_code == 404

def test_delete_book(db):

    # Create an author
    author = Author(name="Test Author")

    db.add(author)
    db.commit()
    db.refresh(author)

    # Create a book
    book = {
        "title": "Book To Delete",
        "author_id": author.id,
        "pages": 200,
        "price": 300
    }

    create_response = client.post(
        "/books/",
        json=book
    )

    assert create_response.status_code == 200

    # Get the newly created book ID
    book_id = create_response.json()["id"]

    # Delete the book
    response = client.delete(
        f"/books/{book_id}"
    )

    assert response.status_code == 200

    # Verify the book is actually gone
    get_response = client.get(
        f"/books/{book_id}"
    )

    assert get_response.status_code == 404

def test_delete_book_not_found(db):

    response = client.delete("/books/99999")

    assert response.status_code == 404